[package]
name = "roget"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
itertools = "0.14.0"
once_cell = "1.21.3"

[profile.release]
debug = true
